default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_28296_development

test:
  <<: *default
  database: furima_28296_test

production:
  <<: *default
  database: furima_28296_production
  username: furima_28296
  password: <%= ENV['FURIMA_28296_DATABASE_PASSWORD'] %>